# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-01 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=512, verbose_name='商品名称')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('image_url', models.URLField(default='')),
                ('reference', models.URLField(blank=True, verbose_name='来源')),
                ('put_on_date', models.DateTimeField(null=True, verbose_name='上架时间')),
                ('watching', models.BooleanField(default=False, verbose_name='关注')),
                ('search_key', models.CharField(default='', max_length=64, verbose_name='检索词')),
                ('next_query_date', models.DateField(default=None, null=True, verbose_name='下一次检索日期')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KongfzInstance',
            fields=[
                ('baseinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.BaseInstance')),
                ('source_id', models.BigIntegerField(unique=True, verbose_name='源站拍卖ID')),
                ('is_auction', models.BooleanField(default=False, verbose_name='是否拍卖')),
                ('stage', models.CharField(choices=[('预览中', '预览中'), ('拍卖中', '拍卖中'), ('出售中', '出售中'), ('已结束', '已结束')], default='拍卖中', max_length=16)),
                ('begin_time', models.DateTimeField(default=None, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
                ('bid_time', models.IntegerField(default=0, verbose_name='参拍次数')),
                ('shop_id', models.BigIntegerField(default=0, verbose_name='商店ID')),
            ],
            options={
                'verbose_name_plural': '空夫子列表',
                'ordering': ['-put_on_date'],
            },
            bases=('collect.baseinstance', models.Model),
        ),
        migrations.CreateModel(
            name='QQBBInstance',
            fields=[
                ('baseinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.BaseInstance')),
                ('source_id', models.BigIntegerField(unique=True, verbose_name='源站拍卖ID')),
                ('is_auction', models.BooleanField(default=False, verbose_name='是否拍卖')),
                ('stage', models.CharField(choices=[('预览中', '预览中'), ('拍卖中', '拍卖中'), ('出售中', '出售中'), ('已结束', '已结束')], default='拍卖中', max_length=16)),
                ('begin_time', models.DateTimeField(default=None, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
                ('bid_time', models.IntegerField(default=0, verbose_name='参拍次数')),
                ('shop_id', models.BigIntegerField(default=0, verbose_name='商店ID')),
            ],
            options={
                'verbose_name_plural': '七七八八',
                'ordering': ['-put_on_date'],
            },
            bases=('collect.baseinstance', models.Model),
        ),
        migrations.CreateModel(
            name='ZhaoInstance',
            fields=[
                ('baseinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.BaseInstance')),
                ('source_id', models.BigIntegerField(unique=True, verbose_name='源站拍卖ID')),
                ('is_auction', models.BooleanField(default=False, verbose_name='是否拍卖')),
                ('stage', models.CharField(choices=[('预览中', '预览中'), ('拍卖中', '拍卖中'), ('出售中', '出售中'), ('已结束', '已结束')], default='拍卖中', max_length=16)),
                ('begin_time', models.DateTimeField(default=None, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(default=None, null=True, verbose_name='结束时间')),
                ('bid_time', models.IntegerField(default=0, verbose_name='参拍次数')),
                ('item_id', models.BigIntegerField(default=0, verbose_name='赵涌内部ID')),
            ],
            options={
                'verbose_name_plural': '赵勇列表',
                'ordering': ['-begin_time'],
            },
            bases=('collect.baseinstance', models.Model),
        ),
        migrations.AddField(
            model_name='baseinstance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_collect.baseinstance_set+', to='contenttypes.ContentType'),
        ),
        migrations.AlterUniqueTogether(
            name='zhaoinstance',
            unique_together=set([('item_id', 'source_id')]),
        ),
    ]
