# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 04:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(default=None, editable=False)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True, editable=False)),
                ('name', models.CharField(max_length=128, verbose_name='商品名称')),
                ('price', models.FloatField(default=0.0, verbose_name='价格')),
                ('image_url', models.URLField(default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KongfzInstance',
            fields=[
                ('baseinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.BaseInstance')),
                ('source_id', models.BigIntegerField(unique=True, verbose_name='源站ID')),
            ],
            options={
                'abstract': False,
            },
            bases=('collect.baseinstance',),
        ),
        migrations.AddField(
            model_name='baseinstance',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_collect.baseinstance_set+', to='contenttypes.ContentType'),
        ),
    ]
