# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseinstance',
            name='reference',
            field=models.URLField(blank=True, verbose_name='来源'),
        ),
    ]
