# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0003_auto_20180213_0537'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kongfzinstance',
            options={'ordering': ['-put_on_date'], 'verbose_name_plural': '孔夫子列表'},
        ),
    ]
