# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-14 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0004_auto_20180213_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='kongfzinstance',
            name='is_auction',
            field=models.BooleanField(default=False, verbose_name='是否拍卖'),
        ),
    ]
