# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0005_kongfzinstance_is_auction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhaoInstance',
            fields=[
                ('baseinstance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='collect.BaseInstance')),
                ('source_id', models.BigIntegerField(unique=True, verbose_name='源站ID')),
                ('is_auction', models.BooleanField(default=False, verbose_name='是否拍卖')),
                ('stage', models.CharField(choices=[('预览', '预览'), ('拍卖', '拍卖'), ('结束', '结束')], default='拍卖', max_length=16)),
            ],
            options={
                'verbose_name_plural': '赵勇列表',
                'ordering': ['-put_on_date'],
            },
            bases=('collect.baseinstance', models.Model),
        ),
        migrations.AlterModelOptions(
            name='kongfzinstance',
            options={'ordering': ['-put_on_date'], 'verbose_name_plural': '空夫子列表'},
        ),
        migrations.AddField(
            model_name='kongfzinstance',
            name='stage',
            field=models.CharField(choices=[('预览', '预览'), ('拍卖', '拍卖'), ('结束', '结束')], default='拍卖', max_length=16),
        ),
    ]
