# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-23 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0006_auto_20180223_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kongfzinstance',
            name='stage',
            field=models.CharField(choices=[('预览', '预览'), ('拍卖中', '拍卖中'), ('结束', '结束')], default='拍卖中', max_length=16),
        ),
        migrations.AlterField(
            model_name='zhaoinstance',
            name='stage',
            field=models.CharField(choices=[('预览', '预览'), ('拍卖中', '拍卖中'), ('结束', '结束')], default='拍卖中', max_length=16),
        ),
    ]
