# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 11:01
from __future__ import unicode_literals

from django.db import migrations

from urllib.parse import urlparse

from octopus.collect.models import KongfzInstance

class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0008_auto_20180306_1822'),
    ]

    def forward_kongfz_retail(apps, schema_editor):
        for instance in KongfzInstance.objects.filter(is_auction = False):
            url = instance.reference
            o = urlparse(url)
            path = str(o.path).strip('/')

            paths = path.split('/')
            if len(paths) != 2:
                continue

            instance.shop_id = paths[0]
            instance.save(update_fields = ['shop_id'])

    operations = [
        migrations.RunPython(
            forward_kongfz_retail,
            migrations.RunPython.noop
        )
    ]
