# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0009_auto_20180306_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinstance',
            name='name',
            field=models.CharField(max_length=256, verbose_name='商品名称'),
        ),
        migrations.AlterUniqueTogether(
            name='zhaoinstance',
            unique_together=set([('item_id', 'source_id')]),
        ),
    ]
