# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 10:36
from __future__ import unicode_literals

import random
from django.db import migrations, models
from django.utils.timezone import datetime, timedelta
from octopus.collect.models import KongfzInstance


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0011_auto_20180307_1334'),
    ]

    def forward_kongfz_retail(apps, schema_editor):
        for instance in KongfzInstance.objects.filter(is_auction = False):
            instance.next_query_date = datetime.today() + timedelta(days = random.randint(0, 5))
            instance.save(update_fields = ['next_query_date'])

    operations = [
        migrations.AddField(
            model_name='baseinstance',
            name='next_query_date',
            field=models.DateField(default=None, verbose_name='下一次检索日期'),
        ),
        migrations.RunPython(
            forward_kongfz_retail,
            migrations.RunPython.noop
        )
    ]
