# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-08 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collect', '0012_baseinstance_next_query_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseinstance',
            name='next_query_date',
            field=models.DateField(default=None, null=True, verbose_name='下一次检索日期'),
        ),
    ]
