# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampcatalog',
            name='face_value',
            field=models.IntegerField(default=20, verbose_name='面值/分'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='gibbons',
            field=models.CharField(default='', max_length=16, verbose_name='吉本斯序号'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='gum',
            field=models.BooleanField(default=True, verbose_name='是否有背胶'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='michael',
            field=models.CharField(default='', max_length=16, verbose_name='米歇尔序号'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='name_eng',
            field=models.CharField(default='', max_length=64, verbose_name='英文名称'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='official',
            field=models.CharField(max_length=32, verbose_name='官方志号'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='period',
            field=models.CharField(choices=[('纪特', '纪特'), ('文革', '文革'), ('编号', '编号'), ('JT', 'JT'), ('编年', '编年')], max_length=16, verbose_name='年代分类'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='scott',
            field=models.CharField(default='', max_length=16, verbose_name='斯科特序号'),
        ),
        migrations.RemoveField(
            model_name='stampcatalog',
            name='print_method',
        ),
        migrations.AlterUniqueTogether(
            name='stampcatalog',
            unique_together=set([('official', 'sequence')]),
        ),
    ]
