# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stampsinglecatalog',
            unique_together=set([('group', 'sequence')]),
        ),
    ]
