# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-13 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stampgroupcatalog',
            options={'verbose_name_plural': '邮票目录'},
        ),
        migrations.AlterField(
            model_name='stampsinglecatalog',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='main.StampGroupCatalog'),
        ),
    ]
