# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181106_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampgroupcatalog',
            name='total_face_value',
            field=models.FloatField(default=20.0, verbose_name='总面值/分'),
        ),
        migrations.AlterField(
            model_name='stampsinglecatalog',
            name='face_value',
            field=models.FloatField(default=8.0, verbose_name='面值/分'),
        ),
    ]
