# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-02-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180204_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampcatalog',
            name='gibbons',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='吉本斯序号'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='michael',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='米歇尔序号'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='name_eng',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='英文名称'),
        ),
        migrations.AlterField(
            model_name='stampcatalog',
            name='scott',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='斯科特序号'),
        ),
    ]
