# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20181106_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsinglecatalog',
            name='image_url',
            field=models.URLField(blank=True, default='', editable=False),
        ),
        migrations.AddField(
            model_name='stampsinglecatalog',
            name='reference',
            field=models.URLField(blank=True, verbose_name='来源'),
        ),
    ]
