# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181107_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='stampsinglecatalog',
            name='old_price_percent',
            field=models.FloatField(default=0.0, verbose_name='旧票全套价格占比'),
        ),
        migrations.AddField(
            model_name='stampsinglecatalog',
            name='price_percent',
            field=models.FloatField(default=0.0, verbose_name='新票全套价格占比'),
        ),
    ]
