# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-07 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181107_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stampsinglecatalog',
            name='old_face_value',
            field=models.FloatField(default=0, verbose_name='改值原面值'),
        ),
    ]
